/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as AdminPedidosRouteImport } from './routes/admin/pedidos'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin/configuracoes'
import { Route as AdminCategoriasRouteImport } from './routes/admin/categorias'
import { Route as AdminProdutosIndexRouteImport } from './routes/admin/produtos/index'
import { Route as AdminProdutosNovoRouteImport } from './routes/admin/produtos/novo'
import { Route as AdminProdutosIdRouteImport } from './routes/admin/produtos/$id'

const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPedidosRoute = AdminPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriasRoute = AdminCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProdutosIndexRoute = AdminProdutosIndexRouteImport.update({
  id: '/produtos/',
  path: '/produtos/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProdutosNovoRoute = AdminProdutosNovoRouteImport.update({
  id: '/produtos/novo',
  path: '/produtos/novo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProdutosIdRoute = AdminProdutosIdRouteImport.update({
  id: '/produtos/$id',
  path: '/produtos/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/produtos': typeof ProdutosRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/product/$id': typeof ProductIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/produtos/$id': typeof AdminProdutosIdRoute
  '/admin/produtos/novo': typeof AdminProdutosNovoRoute
  '/admin/produtos/': typeof AdminProdutosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/produtos': typeof ProdutosRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/product/$id': typeof ProductIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/produtos/$id': typeof AdminProdutosIdRoute
  '/admin/produtos/novo': typeof AdminProdutosNovoRoute
  '/admin/produtos': typeof AdminProdutosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/produtos': typeof ProdutosRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/product/$id': typeof ProductIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/produtos/$id': typeof AdminProdutosIdRoute
  '/admin/produtos/novo': typeof AdminProdutosNovoRoute
  '/admin/produtos/': typeof AdminProdutosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/produtos'
    | '/admin/categorias'
    | '/admin/configuracoes'
    | '/admin/login'
    | '/admin/pedidos'
    | '/product/$id'
    | '/admin/'
    | '/admin/produtos/$id'
    | '/admin/produtos/novo'
    | '/admin/produtos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/produtos'
    | '/admin/categorias'
    | '/admin/configuracoes'
    | '/admin/login'
    | '/admin/pedidos'
    | '/product/$id'
    | '/admin'
    | '/admin/produtos/$id'
    | '/admin/produtos/novo'
    | '/admin/produtos'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/produtos'
    | '/admin/categorias'
    | '/admin/configuracoes'
    | '/admin/login'
    | '/admin/pedidos'
    | '/product/$id'
    | '/admin/'
    | '/admin/produtos/$id'
    | '/admin/produtos/novo'
    | '/admin/produtos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ProdutosRoute: typeof ProdutosRoute
  ProductIdRoute: typeof ProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pedidos': {
      id: '/admin/pedidos'
      path: '/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AdminPedidosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categorias': {
      id: '/admin/categorias'
      path: '/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AdminCategoriasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/produtos/': {
      id: '/admin/produtos/'
      path: '/produtos'
      fullPath: '/admin/produtos/'
      preLoaderRoute: typeof AdminProdutosIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/produtos/novo': {
      id: '/admin/produtos/novo'
      path: '/produtos/novo'
      fullPath: '/admin/produtos/novo'
      preLoaderRoute: typeof AdminProdutosNovoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/produtos/$id': {
      id: '/admin/produtos/$id'
      path: '/produtos/$id'
      fullPath: '/admin/produtos/$id'
      preLoaderRoute: typeof AdminProdutosIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCategoriasRoute: typeof AdminCategoriasRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPedidosRoute: typeof AdminPedidosRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminProdutosIdRoute: typeof AdminProdutosIdRoute
  AdminProdutosNovoRoute: typeof AdminProdutosNovoRoute
  AdminProdutosIndexRoute: typeof AdminProdutosIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCategoriasRoute: AdminCategoriasRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPedidosRoute: AdminPedidosRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminProdutosIdRoute: AdminProdutosIdRoute,
  AdminProdutosNovoRoute: AdminProdutosNovoRoute,
  AdminProdutosIndexRoute: AdminProdutosIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ProdutosRoute: ProdutosRoute,
  ProductIdRoute: ProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
